import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CreateLink from "../components/CreateLink";
import LinkList from "../components/LinkList";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main">
        <LinkList />
        <CreateLink />
      </div>
    </>
  );
};

export default Home;
